# Generated by Django 4.2.7 on 2023-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=100)),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.CharField(max_length=120)),
                ('Amount', models.FloatField()),
                ('MpesaReceiptNumber', models.CharField(max_length=15)),
                ('TransactionDate', models.IntegerField()),
                ('PhoneNumber', models.CharField(max_length=13)),
            ],
        ),
    ]
